import Head from "next/head";

import { HeroParallax } from '../components/HeroParallax'
import { AboutUs } from '../components/AboutUs'
import { FeaturedProducts } from '../components/FeaturedProducts'
import { Footer } from '../components/Footer'
import { GlobalProvider } from '../GlobalContext'

export default function Home() {
  return (
    <>
      <Head>
        <title>Diabolical</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/assets/favicon.ico" />
      </Head>
      <GlobalProvider>
        <main>
          <HeroParallax />
          <AboutUs />
          <FeaturedProducts />
          <Footer />
        </main>
      </GlobalProvider>
    </>
  );
}
